#161404824 Add a readme and feedback bug fixes
kwanj-k/storemanager-v2 pull request #4
Opened 2018-10-27 07:18 UTC by kwanj-k

### What does this PR do?
Add a readme for the repo

#### Description of Task to be Completed?
-- Add a repo read
-- Remove abort and use return 

### How should this be manually tested?
* Navigate  [here](https://github.com/kwanj-k/storemanager-v2/tree/ch-readme-%23161404824)
  and checkout the readme

* Test out the API [here](https://storemanager-v2.herokuapp.com/api/v2)

### What are the relevant Pivotal Tracker stories?
  #161523838

2018-10-29 08:17 UTC, Collins33 requested changes

2018-10-29 08:17 UTC, Collins33 commented on app/api/common/validators.py
> +                #abort(400,msg)
Remove commented out code

2018-10-29 08:17 UTC, Collins33 commented on app/api/common/validators.py
>          if i == 'name':
Use descriptive names for variables

2018-10-30 02:05 UTC, kwanj-k commented on app/api/common/validators.py
> +                #abort(400,msg)
done

2018-10-30 02:05 UTC, kwanj-k commented on app/api/common/validators.py
>          if i == 'name':
done

2018-10-30 17:01 UTC, merged